name: mcu_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  im_stepper: ^1.0.1+1
  eva_icons_flutter: ^3.1.0
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.2.6
  label_marker: ^1.0.1
  rive: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/spider-man-far-from-home.jpg
    - assets/images/scarlett-johansson-black-widow.jpg
    - assets/images/Marvel-Studios-Logo.png
    - assets/images/Marvel Studio.png
    - assets/images/2021-spiderman-no-way-home-5k-xb-800x1280.jpg
    - assets/images/spider-man-far-from-home.jpg
    - assets/images/marvel-doctor-strange-hd-720x1280.jpg
    - assets/images/thor-in-thor-rangnarok-2017-5e-720x1280.jpg
    - assets/images/doctor-strange-in-the-multiverse-of-madness-poster.jpg

    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
